project_id = "jzkdpoaxesfggreojydu"

[functions.seed-stock-data]
verify_jwt = false

[functions.fetch-stock-data]
verify_jwt = false

[functions.api-stocks]
verify_jwt = false

[functions.api-stats]
verify_jwt = false

[functions.api-predict]
verify_jwt = false