// This is a temporary fallback - the real client will be auto-generated by Supabase integration
import { createClient } from "@supabase/supabase-js";

// These environment variables are automatically provided by Lovable's Supabase integration
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl) {
  throw new Error('Missing VITE_SUPABASE_URL environment variable. Please ensure Supabase integration is properly connected.');
}

if (!supabaseAnonKey) {
  throw new Error('Missing VITE_SUPABASE_ANON_KEY environment variable. Please ensure Supabase integration is properly connected.');
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey);